login Screen
istutiagarwal/timble pull request #1
Opened 2024-04-06 13:49 UTC by istutiagarwal

Refers : https://infydex.atlassian.net/jira/software/projects/TMB/boards/6?selectedIssue=TMB-4

Description : Added UI for login onboarding screens.

2024-04-07 16:46 UTC, A1H1 requested changes

2024-04-07 16:46 UTC, A1H1 commented on assets/images/timble_onboarding_image.png
rename it to bg_onboarding.png

2024-04-07 16:46 UTC, A1H1 commented on lib/app/data/values/images.dart
> +  static const icOnboardingBackgroundImage = 'assets/images/timble_onboarding_image.png';
make it bgOnboarding

2024-04-07 16:46 UTC, A1H1 commented on lib/app/modules/auth/onboarding/views/onboarding_view.dart
> +    return BaseOnboardingPage(children: [
move padding inside onboardin page

2024-04-07 16:46 UTC, A1H1 commented on lib/app/modules/auth/views/base_onboarding_page.dart
> +class BaseOnboardingPage extends StatelessWidget {
rename it to BaseOnboardingView

2024-04-07 16:46 UTC, A1H1 commented on lib/app/modules/auth/onboarding/views/onboarding_view.dart
> +          onTap: () {
make it on liner, ex: ()=>code

2024-04-07 16:46 UTC, A1H1 commented on lib/app/modules/auth/login/views/auth_login_view.dart
>  class AuthLoginView extends GetView<AuthLoginController> {
create static method named launch and use it

2024-04-07 16:46 UTC, A1H1 commented on lib/widgets/buttons/filled_round_corner_button.dart
> +      {required this.text, required this.onTap, required this.backgroundColor});
bgColor can be not required, give pink as a default color

2024-04-07 16:46 UTC, A1H1 commented on lib/widgets/buttons/filled_round_corner_button.dart
> +          top: 16.0,
use dimens

2024-04-07 16:46 UTC, A1H1 commented on lib/widgets/buttons/filled_round_corner_button.dart
> +        padding: const EdgeInsets.only(
instead of only use symmetric and give vertical

2024-04-07 16:46 UTC, A1H1 commented on lib/widgets/buttons/filled_round_corner_button.dart
> +      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(35.0)),
use dimen and use even number

2024-04-07 16:46 UTC, A1H1 commented on lib/widgets/buttons/filled_round_corner_button.dart
> +class FilledRoundedCornerButton extends StatelessWidget {
remove corner from name

2024-04-07 16:46 UTC, A1H1 commented on lib/widgets/buttons/rounded_corner_border_button.dart
> +class RoundedCornerBorderButton extends StatelessWidget {
remove corner from name

2024-04-07 16:46 UTC, A1H1 commented on lib/widgets/buttons/rounded_corner_border_button.dart
> +      {required this.text, required this.onTap, required this.borderColor});
give a default value

2024-04-08 06:14 UTC, istutiagarwal commented on assets/images/timble_onboarding_image.png
done

2024-04-08 06:14 UTC, istutiagarwal commented on lib/app/data/values/images.dart
> +  static const icOnboardingBackgroundImage = 'assets/images/timble_onboarding_image.png';
done

2024-04-08 07:03 UTC, istutiagarwal commented on lib/app/modules/auth/views/base_onboarding_page.dart
> +class BaseOnboardingPage extends StatelessWidget {
done

2024-04-08 07:07 UTC, istutiagarwal commented on lib/widgets/buttons/filled_round_corner_button.dart
> +      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(35.0)),
done

2024-04-08 07:11 UTC, istutiagarwal commented on lib/widgets/buttons/rounded_corner_border_button.dart
> +      {required this.text, required this.onTap, required this.borderColor});
done

2024-04-09 05:28 UTC, merged