WIP:TMB-5 - Added Sign up Page
istutiagarwal/timble pull request #3
Opened 2024-04-09 11:33 UTC by S1ncer3ly

To Do :-
get otp page

2024-04-09 11:56 UTC, A1H1 requested changes

2024-04-09 11:56 UTC, A1H1 commented on assets/fonts/RozhaOne-Regular.ttf
make it snake case

2024-04-09 11:56 UTC, A1H1 commented on assets/images/ico_In_flag.png
make it snake case ic_india_flag, also compress it using tinypng

2024-04-09 11:56 UTC, A1H1 commented on lib/app/data/values/images.dart
> +  static const icOnboardingBackgroundImage = 'assets/images/bg_onboarding.png';
its not getting used, its from merge conflict remove it

2024-04-09 11:56 UTC, A1H1 commented on lib/app/data/values/images.dart
> +  static const icSignUpImage = 'assets/images/ic_email.png';
wrong variable name, make icEmail

2024-04-09 11:56 UTC, A1H1 commented on lib/app/data/values/images.dart
> +  static const icInFlag = 'assets/images/ico_In_flag.png';
ic_india_flag

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +        padding: const EdgeInsets.fromLTRB(30, 70, 30, 0),
there is one dimens file use dimentions from there, check any previous page

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                    'What is your mail',
hard coded string

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                    style: TextStyle(fontSize: 32, fontFamily: 'Rozha One'),
move to style file

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                Flexible(
flexile is not required here

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                Flexible(
user expanded

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                  borderRadius: BorderRadius.circular(14),
move number to dimens

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                  borderRadius: BorderRadius.circular(14),
move number to dimens

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                      padding: const EdgeInsets.only(left: 10.0),
padding is not required,  use sized box with width

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                        width: 24,
move to dimnes

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                labelText: ' Email Id *',
move to strings

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +                    EdgeInsets.symmetric(horizontal: 27, vertical: 18),
move to dimens and use even numbers

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +              height: 23,
move to dimens and use even numbers

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +              style: TextStyle(
move to styles

2024-04-09 11:56 UTC, A1H1 commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +              width: 203,
remove width , and avoid hardcoded wdith, use padding instead

2024-04-09 11:56 UTC, A1H1 commented on lib/widgets/buttons/filled_round_button.dart
> +  final double width; // Custom width
remove this

2024-04-09 11:56 UTC, A1H1 commented on lib/widgets/circular_container_with_icon/circular_container_with_icon.dart
> +  final dynamic icon;
data type  should not be dynamic

2024-04-10 12:17 UTC, istutiagarwal commented on lib/app/data/values/images.dart
> +  static const ic_in_flag = 'assets/images/ico_In_flag.png';
please change the name to 'ic_flag_india'  for file name and icFlagIndia for variable name.

2024-04-10 12:24 UTC, istutiagarwal commented on lib/app/modules/auth/signup/views/auth_signup_view.dart
> +              height: 80,
here again

2024-04-10 12:30 UTC, istutiagarwal commented on lib/widgets/circular_container_with_icon/circular_container_with_image.dart
> +    this.borderWidth = 1.0,
here also

2024-04-10 12:30 UTC, istutiagarwal commented on lib/widgets/circular_container_with_icon/circular_container_with_image.dart
> +    this.iconSize = 14,
here also

2024-04-10 12:30 UTC, istutiagarwal commented on lib/widgets/circular_container_with_icon/circular_container_with_image.dart
> +      padding: EdgeInsets.all(4),
here also

2024-04-12 14:07 UTC, merged